# Generated by Django 5.1.3 on 2024-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ericapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
